version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: docker
    #   MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
